version: 2
jobs:
  build-image:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: make build
      - run:
          name: Archive Docker image
          command: make archive-image
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push-image:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login to Docker hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push image
          command: make push

workflows:
  version: 2
  build_push:
    jobs:
      - build-image
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              only:
              - master
